### ISSUE TITLE
Ошибка при компиляции

### ISSUE THREAD

**Issue by andrey1509960** [nekromant/esphome-lctech-4chanel-modules#2]
Пробую компилировать в epshome пишет ошибку
`INFO Reading configuration /config/esphome/gatekeeper.yaml...
INFO Detected timezone 'MSK' with UTC offset 3
Failed config

uart: 
  - [source /config/esphome/gatekeeper.yaml:30]
    
    ID 'uart' conflicts with the name of an esphome integration, please use another ID name.
    id: uart [source /config/esphome/gatekeeper.yaml:30]
    baud_rate: 115200
    tx_pin: GPIO1
    rx_pin: GPIO3`

**Comment by nekromant** [comment]
Вкоммитил свежие изменения, теперь все должно собираться.

**Comment by andrey1509960** [comment]
Спасибо , завтра проверю.
Я в программировании «дуб». 
Вопрос такой , если в секции 
lambda :  |-
  if (id(relay2).state) {
  return true;
  } else {
  return false;
  }
поменять местами true с false , то реле в НА будут отображаться правильно.
У меня сейчас так , если в НА отображается реле включено , то на самом деле реле выключено.
Т.е. инверсивная сработка. По большому счету по барабану , можно использовать др. контакты, но все же... 
>Воскресенье, 31 мая 2020, 13:46 +03:00 от Andrew <notifications@github.com>:
> 
> 
>Вкоммитил свежие изменения, теперь все должно собираться.
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Андрей Шибанов

**Comment by nekromant** [comment]
Емнип, эта инверсия из-за того, что я их инвертировал в своей прошивке nuvoton'а, и лень было переделывать. Поправь в yaml, если надо работать со стоком.

**Comment by andrey1509960** [comment]
Спасибо. 
Понял, поправлю.
--
Отправлено из Mail.ru для Android вторник, 02 июня 2020г., 11:06 +03:00 от Andrew  notifications@github.com :
